### ISSUE TITLE
New varients

### ISSUE THREAD

**Issue by 15987632** [DrkMatr1984/EggCatcher#2]
Some new variants would be for rabbit colors, charged for creepers, and elder for guardian

**Comment by DrkMatr1984** [comment]
Add variants for all 3 of these listed above. In Addition, I have also reworked the way the plugin "kills" the entities when they are captured to prevent negative interactions with other plugins. Lastly, I've added the ability to catch mobs by walking up to them and left-clicking, or "hitting" them, with an Egg, instead of requiring the egg to be thrown. 
Please test out some of the new features!
Also, the ElderGuardian Variant has it's own unique capture chances, prices, etc in the configs.
